WINDOW_TITLE = "El Hareketi Tanıma"

PANEL_TITLE = "Kontrol Paneli"
APP_HEADER_TITLE = "El Hareketi Tanıma Sistemi"
APP_HEADER_SUBTITLE = "Gerçek zamanlı tek-el jest analizi"
VIDEO_TITLE = "Canlı Kamera Akışı"
VIDEO_IDLE_HINT = "Kamerayı başlatmak için sağdaki butonu kullanın"
VIDEO_STOPPED = "Kamera durduruldu"
CAMERA_OPEN_ERROR = "Kamera açılamadı. Lütfen cihaz iznini kontrol edin."

LABEL_GESTURE_WAITING = "Bekleniyor"
LABEL_NO_HAND = "El Algılanmadı"
LABEL_GESTURE_PREFIX = "Hareket"
LABEL_CONFIDENCE_PREFIX = "Güven"
LABEL_FPS_PREFIX = "FPS"

BUTTON_START = "Kamerayı Başlat"
BUTTON_STOP = "Kamerayı Durdur"
HISTORY_TITLE = "Hareket Geçmişi"
STATUS_READY = "Hazır"
STATUS_RUNNING = "Kamera Aktif"
STATUS_CAMERA_ERROR = "Kamera Hatası"
SHORTCUT_HINT = "Kısayollar: Space Başlat/Durdur, Esc Çıkış"

GESTURE_OK = "OK İşareti"
GESTURE_PINCH = "Pinch"
GESTURE_THUMBS_UP = "Başparmak Yukarı"
GESTURE_THUMBS_DOWN = "Başparmak Aşağı"
GESTURE_V = "V İşareti"
GESTURE_TWO = "İki Parmak"
GESTURE_THREE = "Üç Parmak"
GESTURE_FOUR = "Dört Parmak"
GESTURE_GUN = "Silah İşareti"
GESTURE_CALL_ME = "Call Me"
GESTURE_ROCK = "Rock İşareti"
GESTURE_OPEN_HAND = "Açık El"
GESTURE_FIST = "Yumruk"
GESTURE_POINT = "İşaret"
GESTURE_UNKNOWN = "Bilinmiyor"
GESTURE_SWIPE_RIGHT = "Swipe Sağa"
GESTURE_SWIPE_LEFT = "Swipe Sola"
GESTURE_SWIPE_DOWN = "Swipe Aşağı"
GESTURE_SWIPE_UP = "Swipe Yukarı"

INFO_TEXT = (
    "Desteklenen hareketler:\n"
    "- Açık El\n"
    "- Yumruk\n"
    "- Başparmak Yukarı\n"
    "- Başparmak Aşağı\n"
    "- İşaret\n\n"
    "- V İşareti / İki Parmak\n"
    "- Üç Parmak / Dört Parmak\n"
    "- OK İşareti / Pinch\n"
    "- Rock / Call Me / Silah\n"
    "- Swipe Sola-Sağa-Yukarı-Aşağı\n\n"
    "Not: Daha iyi sonuç için\n"
    "yeterli ışık kullanın."
)
